language: c
env:
  - BD=esp8266:esp8266:d1_mini:xtal=80,eesz=4M3M
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.10-linux64.tar.xz
  - tar xf arduino-1.8.10-linux64.tar.xz
  - sudo mv arduino-1.8.10 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/MiP_ESP8266_Library
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - git clone https://github.com/squix78/json-streaming-parser /usr/local/share/arduino/libraries/json-streaming-parser
  - arduino --install-boards esp8266:esp8266
  - arduino --board $BD --save-prefs
  - arduino --pref "compiler.warning_level=all" --save-prefs
script:
  - "echo $PWD"
  - "echo $HOME"
  - "ls $PWD"
  - arduino --verify --board $BD $PWD/examples/BareMinimumWifi/BareMinimumWifi.ino
  - arduino --verify --board $BD $PWD/examples/ChestLED/ChestLED.ino
  - arduino --verify --board $BD $PWD/examples/Clap/Clap.ino
  - arduino --verify --board $BD $PWD/examples/ContinuousDrive/ContinuousDrive.ino
  - arduino --verify --board $BD $PWD/examples/DistanceDrive/DistanceDrive.ino
  - arduino --verify --board $BD $PWD/examples/DriveForwardBackward/DriveForwardBackward.ino
  - arduino --verify --board $BD $PWD/examples/EnableGameMode/EnableGameMode.ino
  - arduino --verify --board $BD $PWD/examples/EnableMiPDetectionMode/EnableMiPDetectionMode.ino
  - arduino --verify --board $BD $PWD/examples/FallDown/FallDown.ino
  - arduino --verify --board $BD $PWD/examples/Gesture/Gesture.ino
  - arduino --verify --board $BD $PWD/examples/GestureRadarMode/GestureRadarMode.ino
  - arduino --verify --board $BD $PWD/examples/GetUp/GetUp.ino
  - arduino --verify --board $BD $PWD/examples/GmailNotifierWifi/GmailNotifierWifi.ino
  - arduino --verify --board $BD $PWD/examples/HeadLEDs/HeadLEDs.ino
  - arduino --verify --board $BD $PWD/examples/Odometer/Odometer.ino
  - arduino --verify --board $BD $PWD/examples/PlaySound/PlaySound.ino
  - arduino --verify --board $BD $PWD/examples/Radar/Radar.ino
  - arduino --verify --board $BD $PWD/examples/RawSendReceive/RawSendReceive.ino
  - arduino --verify --board $BD $PWD/examples/ReadIRDongleCode/ReadIRDongleCode.ino
  - arduino --verify --board $BD $PWD/examples/ReadWriteEeprom/ReadWriteEeprom.ino
  - arduino --verify --board $BD $PWD/examples/SPIFFS/SPIFFS.ino
  - arduino --verify --board $BD $PWD/examples/SRSdemo/SRSdemo.ino
  - arduino --verify --board $BD $PWD/examples/SendIRDongleCode/SendIRDongleCode.ino
  - arduino --verify --board $BD $PWD/examples/Shake/Shake.ino
  - arduino --verify --board $BD $PWD/examples/Sleep/Sleep.ino
  - arduino --verify --board $BD $PWD/examples/SoftwareHardwareVersion/SoftwareHardwareVersion.ino
  - arduino --verify --board $BD $PWD/examples/Status/Status.ino
  - arduino --verify --board $BD $PWD/examples/Stop/Stop.ino
  - arduino --verify --board $BD $PWD/examples/TelnetDebug/TelnetDebug.ino
  - arduino --verify --board $BD $PWD/examples/TimeWifi/TimeWifi.ino
  - arduino --verify --board $BD $PWD/examples/TurnLeftRight/TurnLeftRight.ino
  - arduino --verify --board $BD $PWD/examples/Volume/Volume.ino
  - arduino --verify --board $BD $PWD/examples/WeatherEmailFinalWifi/WeatherEmailFinalWifi.ino
  - arduino --verify --board $BD $PWD/examples/WeatherStationFinalWifi/WeatherStationFinalWifi.ino
  - arduino --verify --board $BD $PWD/examples/WeatherStationSerialWifi/WeatherStationSerialWifi.ino
  - arduino --verify --board $BD $PWD/examples/WeatherStationTelnetWifi/WeatherStationTelnetWifi.ino
  - arduino --verify --board $BD $PWD/examples/WeatherStationWebWifi/WeatherStationWebWifi.ino
  - arduino --verify --board $BD $PWD/examples/WeatherStationWifi/WeatherStationWifi.ino
  - arduino --verify --board $BD $PWD/examples/Weight/Weight.ino
  - arduino --verify --board $BD $PWD/examples/ZeroEeprom/ZeroEeprom.ino
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: change
    on_failure: change
