name=MiP Power Up: D1 mini
version=1.0.1
author=Community
maintainer=Samuel Trassare <tiogaplanet@users.noreply.github.com>
sentence=An API to enable connecting the Wemos D1 mini and clones to the WowWee MiP robot.
paragraph=This library, named MiP Power Up: D1 mini, along with its associated adapter board of the same name, enables easy programming of the D1 mini, an ESP8266-based microcontroller, when connected to MiP via serial port. With the D1 mini, MiP is transformed into an Internet-connected robot, drastically increasing its capability.
category=Device Control
url=https://github.com/Tiogaplanet/MiP_Power_Up_D1_mini
architectures=esp8266
